### ISSUE TITLE
snapshot-validation-webhook-test-valid-body is failing

### ISSUE THREAD

**Issue by rrey-aviatrix** [piraeusdatastore/helm-charts#11]
Installed snapshot-validation-webhook-1.4.3 (app version v6.0.1) which is properly deployed:
```
NAME                       	NAMESPACE           	REVISION	UPDATED                              	STATUS  	CHART                            	APP VERSION
snapshot-validation-webhook	external-snapshotter	1       	2022-06-07 17:54:25.994741 +0200 CEST	deployed	snapshot-validation-webhook-1.4.3	v6.0.1
```

when running `helm test snapshot-validation-webhook` the operation fails:
```
Error: pod snapshot-validation-webhook-test-valid-body failed
```

**Comment by rrey-aviatrix** [comment]
I made a test where I replaced all occurrences of `v1beta1` in the query and the test succeeded but I honestly don't know if that makes sense :/

**Comment by WanzenBug** [comment]
I think the issue is that `v1beta1` versions were removed from CRDs for the 6.0.1 release. They added them back in the meantime. But we should just update to `v1`.

**Comment by rrey-aviatrix** [comment]
I only tested through curl and did not test end to end with helm test again :/

**Comment by WanzenBug** [comment]
Fixed it now. Seems like the test is just no longer relevant, as the webhook no longer checks for the condition that should have caused a failure. I believe this is because the new CRD version already ensures this. So I switched to a different check.
