### ISSUE TITLE
Missing enable-distributed-snapshotting support

### ISSUE THREAD

**Issue by aonnikov** [piraeusdatastore/helm-charts#12]
External Snapshotter v5.0.0 introduces an ability to create "distributed" snapshots. These are snapshots of volumes that are  bound to a specific node. The feature is enabled by adding `enable-distributed-snapshotting` arg to the external snapshotter container.

**Comment by WanzenBug** [comment]
We could probably just use a free-form arguments dictionary for the snapshot-controller.

**Comment by aonnikov** [comment]
Yeah, it could be a free-form arguments dictionary that defaults to the current arguments dict (leader election config).

**Comment by WanzenBug** [comment]
Included in the latest release. Use `--set args.enableDistributedSnapshotting=true`.
