### ISSUE TITLE
snapshot-controller chart: Add possiblity to override default Chart name and fullname

### ISSUE THREAD

**Issue by lukastopiarz** [piraeusdatastore/helm-charts#46]
Hi,
firstly, thanks for the great helm chart which is handy as there is no official one provided by kubernetes-csi/external-snapshotter project.

What about adding the possibility of overriding the "name" and "fullName" which are taken from the Chart name?
So one could specify **Values.fullnameOverride** and **Values.nameOverride** variables which could override resource names which are usually derived from Chart name and release during templating.

Motivation: I cannot set Chart release name in our templating pipeline. Other charts we use have the possibility of name override. Kyverno helm chart as example:
https://github.com/kyverno/kyverno/blob/main/charts/kyverno/templates/_helpers/_names.tpl

It would probably need something like this in the helper file:
```
{{- define "snapshot-controller.fullname" -}}
{{- if .Values.fullnameOverride -}}
{{- .Values.fullnameOverride | trunc 63 | trimSuffix "-" -}}
{{- else -}}
{{- if contains .Chart.Name .Release.Name }}
{{- .Release.Name | trunc 63 | trimSuffix "-" }}
{{- else }}
{{- printf "%s-%s" .Release.Name .Chart.Name | trunc 63 | trimSuffix "-" }}
{{- end }}
{{- end }}
```

**Comment by WanzenBug** [comment]
Just pushed f8a6ac078f97382c8dd46a603ddc0668135877b7, so you can set `controller.fullnameOverride` and `webhook.fullnameOverride`.

**Comment by lukastopiarz** [comment]
@WanzenBug good job, thanks. Could you please backport this also to chart version 2.0.4? We use snapshot controller 6.3.x as it is the latest stable version according to the Kubernetes-CSI web.

**Comment by WanzenBug** [comment]
I don't really see the need to backport anything. If anything it's probably the Kubernetes-CSI page that needs updating. We generally follow the release of the snapshot-controller directly: https://github.com/kubernetes-csi/external-snapshotter/releases/
