### ISSUE TITLE
Make CRDs part of helm charts

### ISSUE THREAD

**Issue by z0rc** [piraeusdatastore/helm-charts#5]
CRDs outside of chart make installation via CI pipelines rather tedious process, as we need to manage CRD lifecycle separately from rest of the chart.

**Comment by WanzenBug** [comment]
Hi!

Having CRDs outside the chart was a deliberate choice on my part. My reasons are:
* Helm doesn't upgrade CRDs. After the initial installation, users would still have to run `kubectl replace -f ....`. See [here](https://helm.sh/docs/chart_best_practices/custom_resource_definitions/#method-1-let-helm-do-it-for-you)
* We'd need to include the CRDs in this repo, meaning more work to keep the Chart in sync.

**Comment by z0rc** [comment]
Thing is CI/CD tools (like helmfile, ArgoCD) that work with helm charts can handle CRDs upgrades (they are using `helm install` under hood instead of `helm upgrade`). Or as helm docs recommends, move CRDs into their own helm chart.
