### ISSUE TITLE
Addition of kubeVersion logic in Chart.yaml does not work for AWS EKS versioning

### ISSUE THREAD

**Issue by mcontario** [piraeusdatastore/helm-charts#52]
While attempting upgrade to chart 3.0.3, we encountered the following error regarding kubeVersion: 
`Error: UPGRADE FAILED: chart requires kubeVersion: >= 1.25 which is incompatible with Kubernetes v1.29.4-eks-036c24b`

Probably needs changed to something like this: 
`kubeVersion: ">= 1.25.0-0"`

**Comment by WanzenBug** [comment]
Thanks for the report. Should be fixed with 2cf6451ad0cbc071e875f5282e2a0a7286f54fef. Seems like surprising behaviour for this check.
