### ISSUE TITLE
Issue with argo-cd upgrade

### ISSUE THREAD

**Issue by jonathon2nd** [piraeusdatastore/helm-charts#54]
Chart: snapshot-controller:4.0.0
Default values

Getting the following errors
```
apiextensions.k8s.io/v1/CustomResourceDefinition
linstor
volumegroupsnapshotclasses.groupsnapshot.storage.k8s.io
SyncFailed
CustomResourceDefinition.apiextensions.k8s.io "volumegroupsnapshotclasses.groupsnapshot.storage.k8s.io" is invalid: status.storedVersions[0]: Invalid value: "v1alpha1": must appear in spec.versions
apiextensions.k8s.io/v1/CustomResourceDefinition
linstor
volumegroupsnapshotcontents.groupsnapshot.storage.k8s.io
SyncFailed
CustomResourceDefinition.apiextensions.k8s.io "volumegroupsnapshotcontents.groupsnapshot.storage.k8s.io" is invalid: status.storedVersions[0]: Invalid value: "v1alpha1": must appear in spec.versions
apiextensions.k8s.io/v1/CustomResourceDefinition
linstor
volumegroupsnapshots.groupsnapshot.storage.k8s.io
SyncFailed
CustomResourceDefinition.apiextensions.k8s.io "volumegroupsnapshots.groupsnapshot.storage.k8s.io" is invalid: status.storedVersions[0]: Invalid value: "v1alpha1": must appear in spec.versions
```

Even when I attempt to replace and force
![image](https://github.com/user-attachments/assets/fd3ddeb2-b8b2-426a-8563-974a8cd7c69d)

**Comment by WanzenBug** [comment]
Looks like this is something done intentionally by the [upstream project](https://github.com/kubernetes-csi/external-snapshotter/pull/1150) :facepalm: 

> This PR entirely removes the capability to serve the v1alpha version. Existing clients will be broken.
This is consistent with the https://github.com/kubernetes-csi/external-snapshotter/pull/1150#discussion_r1852973872 and the related https://github.com/kubernetes-csi/external-snapshotter/pull/1150#discussion_r1853037522.

**Comment by WanzenBug** [comment]
Note: I closed this issue here, as this is not really the place to fix the issue. If there are any workarounds found, they can still be added here.

**Comment by jonathon2nd** [comment]
See: https://github.com/kubernetes-csi/external-snapshotter/pull/1150#issuecomment-2557947586

**Comment by WanzenBug** [comment]
I guess we could try to configure a `pre-upgrade` or `pre-install` hook for this :thinking:
