### ISSUE TITLE
Missing features

### ISSUE THREAD

**Issue by z0rc** [piraeusdatastore/helm-charts#6]
Unable to set via chart values:
- Pod's `resources.limits`
- Pod's `topologySpreadConstrains`
- `PodDisruptionBudget` policies

**Comment by WanzenBug** [comment]
>    Pod's `resources.limits`

I'm pretty sure setting `resources` is supported?

>    Pod's topologySpreadConstrains

True, I would be open to PRs on this.

>    PodDisruptionBudget policies

On this I am less sure. Do you have insight how other charts handle this?

**Comment by z0rc** [comment]
> I'm pretty sure setting resources is supported?

Yeah, oversight on my side, sorry.

> On this I am less sure. Do you have insight how other charts handle this?

https://github.com/traefik/traefik-helm-chart/pull/192 as example.

**Comment by z0rc** [comment]
Closed by https://github.com/piraeusdatastore/helm-charts/pull/15, thanks!
